[platformio]
default_envs = esp32s3_heltec, esp32c5_xiao

[env:esp32s3_heltec]
platform = espressif32@6.5.0
board = heltec_wifi_lora_32_v3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
; S3 firmware (s3_main.ino)
; Heltec V3 Wireless Stick: SX1262 LoRa, OLED, SPI

[env:esp32c5_xiao]
platform = espressif32@6.5.0
board = xiao_esp32c5
framework = arduino
upload_speed = 921600
monitor_speed = 115200
; C5 firmware (c5_main.ino)
; XIAO ESP32-C5 Mini: 5GHz WiFi, SD card slot
